cronos-labs/play-unreal-plugin

CronosPlaySdk/Plugins/CronosPlayUnreal/Source/CronosPlayUnreal/CronosPlayUnreal.Build.cs
CronosPlaySdk/copydll.sh

Problem: missing guide for dylib loading (fix #64)

---

CronosPlaySdk/Plugins/CronosPlayUnreal/CronosPlayUnreal.uplugin

adding EngineVersion 4.27.2

---

CronosPlaySdk/Plugins/CronosPlayUnreal/Source/CronosPlayUnreal/Private/DefiWalletCoreActor.cpp

Problem: incorrect tokenid in tokenuri (fix #73)

---

Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp

Fix usermessage not being set in SignPersonalBlocking

Fix SignPersonalBlocking

---

Source/CronosPlayUnreal/Private/PlayCppSdkBPLibrary.cpp

Solution: support ue5
conditional compiling by major version

Problem: compiling not working on ue5 (fix #97)

---

Content/BP_Cronos.uasset
Content/BP_WalletConnect.uasset
Content/WBP_NftErc1155UI1.uasset
Content/WBP_NftErc721UI.uasset
Content/WBP_PageUI.uasset
Content/WBP_WalletConnectUI.uasset
Makefile
Source/CronosPlayUnreal/Private/PlayCppSdkBPLibrary.cpp
Source/CronosPlayUnreal/Private/PlayCppSdkDownloader.cpp
Source/CronosPlayUnreal/Public/PlayCppSdkBPLibrary.h
Source/CronosPlayUnreal/Public/PlayCppSdkDownloader.h
ThirdParty/cronosplay/include/defi-wallet-core-cpp/src/core.cc
ThirdParty/cronosplay/include/defi-wallet-core-cpp/src/lib.rs.h

Solution: add blueprint asset to plugin
set http agent for http downloading, cronos rpc apis ( CronosPlay-UnrealEngine-Agent )

Problem: no blueprint asset in plugin (fix #94)

---

CHANGELOG.md

Problem: not updated changelog for v0.0.3-alpha (fix #103)

---

CronosPlayUnreal.uplugin

Problem: Missing unreal 5 EngineVersion support (fix #109)

---

.github/workflows/release.yml

Problem: Project contains no unused folders or assets (fix #111)

---

Source/CronosPlayUnreal/Private/DefiWalletCoreActor.cpp
Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp
Source/CronosPlayUnreal/Public/DefiWalletCoreActor.h

Problem: missing api for new_wallet, approve_for_all etc. (fix #105)

---

README.md

Problem: Outdated build procedures in README (fix #115)

---

CHANGELOG.md
Content/CronosPlayUnreal/Blueprint/BP_Cronos.uasset
Content/CronosPlayUnreal/Blueprint/BP_WalletConnect.uasset
Content/CronosPlayUnreal/Blueprint/WBP_NftErc1155UI1.uasset
Content/CronosPlayUnreal/Blueprint/WBP_NftErc721UI.uasset
Content/CronosPlayUnreal/Blueprint/WBP_PageUI.uasset
Content/CronosPlayUnreal/Blueprint/WBP_WalletConnectUI.uasset
Makefile
Source/CronosPlayUnreal/Private/DefiWalletCoreActor.cpp
Source/CronosPlayUnreal/Public/DefiWalletCoreActor.h
Source/ThirdParty/cronosplay/include/defi-wallet-core-cpp/src/core.cc
Source/ThirdParty/cronosplay/include/defi-wallet-core-cpp/src/lib.rs.h

restore blueprint connections
update include
add get_backup_mnemonics, generate_mnemonics
added thirdparty library through lfs
use play-cpp-sdk v0.0.4-alpha

Problem: missing api of get_backup_mnemonics (fix #117)

---

.github/workflows/dev.yml
CronosPlayUnreal.uplugin
Makefile
Source/CronosPlayUnreal/CronosPlayUnreal.Build.cs

Problem: Missing linux support (fix #121)

---

Source/CronosPlayUnreal/Public/DefiWalletCoreActor.h

Problem: incorrect comment for cronos SendAmount (fix #136)

---

CHANGELOG.md

Problem: CHANGELOG is not updated for v0.0.7-alpha (fix #154)

---

Source/CronosPlayUnreal/Public/DefiWalletCoreActor.h
Source/CronosPlayUnreal/Public/PlayCppSdkBPLibrary.h

Problems: Typos and incorrect display name (fix #163)

---

Source/CronosPlayUnreal/Public/DefiWalletCoreActor.h
Source/CronosPlayUnreal/Public/PlayCppSdkBPLibrary.h

Problem: Incorrect functions descriptions and params (fix #173)

---

CHANGELOG.md
CronosPlayUnreal.uplugin

Problem: CHANGELOG is not updated for v0.0.8-alpha (fix #176)

---

CronosPlayUnreal.uplugin

Problem: Incorrect DocsURL (fix #179)

---

.github/workflows/dev.yml
Source/CronosPlayUnreal/Private/DefiWalletCoreActor.cpp

Problem: User agent does not setup by default (fix #167)

---

SECURITY.md

Close:
- #191
Solution:
- Remove Bounty Program

Problem: Bounty Program is not applicable for cronos play (fix #191)

---

README.md
Source/CronosPlayUnreal/Private/DefiWalletCoreActor.cpp
Source/CronosPlayUnreal/Public/DefiWalletCoreActor.h

Problem: Naming of InitializeWallet and InitializeNewDevelopmentOnlyWallet are confusing (fix #171)

---

CHANGELOG.md
CronosPlayUnreal.uplugin
Makefile
Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp
Source/CronosPlayUnreal/Public/PlayCppSdkActor.h
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/contract.rs.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/contract.rs.h
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/core.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/lib.rs.h
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/nft.rs.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/nft.rs.h
Source/ThirdParty/PlayCppSdkLibrary/Include/extra-cpp-bindings/src/lib.rs.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/extra-cpp-bindings/src/lib.rs.h
Source/ThirdParty/PlayCppSdkLibrary/Include/pay.h

Problem: CHANGELOG for v0.0.9-alpha is not updated (fix #193)

---

.github/workflows/cpp-lint.yml
.github/workflows/semgrep.yml

Solution: added cpp-lint and semgrep

Problem: missing C++ linting CI action

---

Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp
Source/CronosPlayUnreal/Private/Utlis.cpp
Source/CronosPlayUnreal/Public/DefiWalletCoreActor.h
Source/CronosPlayUnreal/Public/PlayCppSdkActor.h
Source/CronosPlayUnreal/Public/Utlis.h

Close:
- #199
Solutions:
- Add chain_id to function: SignEip155Transaction
- Rename FInitializeWalletConnectBlockingDelegate to FInitializeWalletConnectDelegate
- Rename EnsureSessionBlocking to EnsureSession
- Add GetCryptoWalletUrl
- Turn SignPersonalBlocking into async SignPersonal
- Rename SignEip155TransactionBlocking to SignEip155Transaction
- Add Utils
- Add ToHex function
- Fix docs

Problem: Missing chain_id for SignEip155Transaction (fix #199)

---

CronosPlayUnreal.uplugin
Makefile
Source/CronosPlayUnreal/Private/DefiWalletCoreActor.cpp
Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp
Source/CronosPlayUnreal/Private/PlayCppSdkBPLibrary.cpp
Source/ThirdParty/PlayCppSdkLibrary/PlayCppSdkLibrary.Build.cs

Problem: Missing ios support (fix #204)

---

Source/CronosPlayUnreal/CronosPlayUnreal.Build.cs
Source/CronosPlayUnreal/Private/DefiWalletCoreActor.cpp

Close:
- #195
Solution:
- Consolidate Engine Version, Platform Name, and Plugin Version Name into user agent

Problem: Can not distinguish user agent from different clients (fix #195)

---

Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp
Source/CronosPlayUnreal/Private/PlayCppSdkBPLibrary.cpp
Source/CronosPlayUnreal/Public/PlayCppSdkActor.h

Close:
- #169
Solutions:
- Save session to a sessioninfo.json file under Saved dir
- Restore session info sessioninfo.json file
- Add a function: `ConnectWalletConnect` 
- Add a function: `ClearSession`
- Breaking change: remove the address and chain_id in walletconnect related functions.

Problem: SaveClient does not save session to local file (Fix #169)

---

.clang-format

Problem: .clang-format is missing (fix #227)

---

CHANGELOG.md

Solution: new release to v0.0.10

Problem: version not updated to v0.0.10 (fix #241)

---

.github/CODEOWNERS

Solution: Added codeowners file

Problem: missing codeowners

---

.github/workflows/cpp-lint.yml
Makefile

Problem: CPP linter is not correctly setup for unreal project (fix #212)

---

.github/workflows/cpp-lint.yml
.github/workflows/dev-ue4_27.yml
.github/workflows/dev-ue5_0.yml
.github/workflows/dev-ue5_1.yml
.github/workflows/release.yml
.github/workflows/semgrep.yml

Solution: added the merge group event on actions

Problem: CI not triggered on merge queues

---

Source/CronosPlayUnreal/Private/DefiWalletCoreActor.cpp

Problem: no need to have a wallet to call GetEthBalance (fix #268)

---

CHANGELOG.md
Makefile
Source/CronosPlayUnreal/Android.xml
Source/CronosPlayUnreal/Android/SecureStorage.java
Source/CronosPlayUnreal/CronosPlayUnreal.Build.cs
Source/CronosPlayUnreal/Private/DefiWalletCoreActor.cpp
Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp
Source/CronosPlayUnreal/Public/DefiWalletCoreActor.h
Source/CronosPlayUnreal/Public/PlayCppSdkActor.h
Source/ThirdParty/PlayCppSdkLibrary/Include/android.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/android.h
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/core.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/lib.rs.h
Source/ThirdParty/PlayCppSdkLibrary/Include/extra-cpp-bindings/src/lib.rs.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/extra-cpp-bindings/src/lib.rs.h

Solution: add secure storage apis

Problem: no secure secret storage option (fix #217)

---

CHANGELOG.md
CronosPlayUnreal.uplugin

Problem: missing release of v0.0.11 (fix #272)

---

install-play-cpp-sdk.bat

Problem: play-cpp-sdk v0.0.16-alpha is not used in windows (fix #282)

---

Makefile
install-play-cpp-sdk.bat

Problem: Does not use play-cpp-sdk v0.0.17-alpha (fix #291)

---

Makefile
Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp
Source/CronosPlayUnreal/Public/PlayCppSdkActor.h
Source/ThirdParty/PlayCppSdkLibrary/Include/extra-cpp-bindings/src/lib.rs.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/extra-cpp-bindings/src/lib.rs.h
install-play-cpp-sdk.bat

Problem: Missing SendEip155Transaction (fix #294)

---

Makefile
Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp
Source/CronosPlayUnreal/Private/Utlis.cpp
Source/CronosPlayUnreal/Public/PlayCppSdkActor.h
Source/CronosPlayUnreal/Public/Utlis.h
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/contract.rs.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/core.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/ethereum.rs.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/nft.rs.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/extra-cpp-bindings/src/lib.rs.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/extra-cpp-bindings/src/lib.rs.h
Source/ThirdParty/PlayCppSdkLibrary/Include/rust/cxx.h
install-play-cpp-sdk.bat

Problem: missing send_contract_transaction bindings (fix #302)

---

Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp

Problem: Incorrect error logs (fix #304)

---

CHANGELOG.md
CronosPlayUnreal.uplugin

Problem: Missing v0.0.12-alpha release (fix #311)

---

Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp
Source/CronosPlayUnreal/Public/PlayCppSdkActor.h

Problem: missing update for wc 2.0 api (fix #326)

---

CHANGELOG.md
CronosPlayUnreal.uplugin
Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp
Source/ThirdParty/PlayCppSdkLibrary/PlayCppSdkLibrary.Build.cs

ignore polling exception
version 0.0.17

Problem: compile error on windows build (fix #338)

---

.github/workflows/release.yml
CHANGELOG.md

Problem: missing UE 5.3 version release (fix #344)

---

.github/workflows/cpp-lint.yml
.github/workflows/dev.yml
CHANGELOG.md
Makefile

Solution: use play-cpp-sdk v0.0.26
in eth_sendTransaction, if `data` is empty, set "data":"0x"

Problem: missing support of defiwallet (fix #349)

---

CHANGELOG.md
Makefile
Source/CronosPlayUnreal/Private/DynamicContractObject.cpp
Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp
Source/CronosPlayUnreal/Public/PlayCppSdkActor.h
Source/CronosPlayUnreal/Public/Utlis.h
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/contract.rs.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/contract.rs.h
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/core.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/ethereum.rs.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/ethereum.rs.h
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/lib.rs.h
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/nft.rs.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/nft.rs.h
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/uint.rs.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/defi-wallet-core-cpp/src/uint.rs.h
Source/ThirdParty/PlayCppSdkLibrary/Include/extra-cpp-bindings/src/lib.rs.cc
Source/ThirdParty/PlayCppSdkLibrary/Include/extra-cpp-bindings/src/lib.rs.h
Source/ThirdParty/PlayCppSdkLibrary/Include/rust/cxx.h

Problem: missing verify function for personal_sign (fix #354)

---

CHANGELOG.md
CronosPlayUnreal.uplugin
install-play-cpp-sdk.bat

Problem: change log not updated (fix #357)
